### ISSUE TITLE
Include annotation data in initial page load

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#35]
I tried to show someone one of the climatefeedback.org articles this morning but the annotations failed to load in Via - https://via.hypothes.is/http://www.rollingstone.com/politics/news/the-point-of-no-return-climate-change-nightmares-are-already-here-20150805?page=2

Chrome console output:

```
The key "target-densitydpi" is not supported.
https://via.hypothes.is/im_///segapi.quantserve.com/seg/r;a=p-41yObSuSE7DTI…krxd.net/data.gif?_kdpid=60658cab-0a68-42f9-a299-b4dee97e21c4&segs=!qcsegs Failed to load resource: the server responded with a status of 400 (Bad Live Resource)
the-point-of-no-return-climate-change-nightmares-are-already-here-20150805?page=3:66 Uncaught Error: invalid version specified
15wombat.js:1588 Skipping www.rollingstone.com not http:/
30wombat.js:1588 Skipping www.rollingstone.com not apis.google.com/se/0/wm/1
https://hypothes.is/api/token?assertion=12b6ee3dd57d7ef330ddd2a9baa93ab978dd604f Failed to load resource: the server responded with a status of 401 (Unauthorized)
wombat.js:1809 DOMException: Blocked a frame with origin "https://via.hypothes.is" from accessing a cross-origin frame.
    at Error (native)
    at init_iframe_wombat (https://via.hypothes.is/static/__pywb/wombat.js:1805:48)
    at HTMLIFrameElement.getter [as contentWindow] (https://via.hypothes.is/static/__pywb/wombat.js:1351:13)
    at f (https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…ntId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:166:214)
    at f (https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…ntId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:166:458)
    at b (https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…ntId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:164:119)
    at g (https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…ntId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:166:512)
    at Object.calcDims (https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…entId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:167:84)
    at Object.n [as getDims] (https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…ntId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:109:143)
    at https://via.hypothes.is/js_/https://pixel.adsafeprotected.com/jload?anId=79…ntId=35781163&adsafe_par&bidurl=${SITE_URL}=${SITE_URL}&adsafe_par:112:124
```

Aside from fixing the issues here, I think it would be worth investigating including the annotations in the initial payload that comes down from the site, preferably directly in the rendered HTML, so that they always work even if there are issues on the client contacting the H APIs.

**Comment by robertknight** [comment]
Full error log from Chrome - https://gist.github.com/robertknight/25241cf069fe117d775d

**Comment by tilgovi** [comment]
Huh... I can't reproduce it.
